//! The implementation of `#[reiny::main]`.
//!
//! Re-exported from the `reiny` umbrella crate as `pub use reiny_macros::main;`, so downstream code
//! writes `#[reiny::main]`. The expansion does two jobs:
//!
//! 1. **Pull in the generated types** — the `publications` / `dependencies` / `internals` modules
//!    that `reiny-build` (from each launch's `build.rs`) wrote to `$OUT_DIR/reiny_generated.rs` are
//!    brought into the crate root. That is what makes `use crate::publications::Ping;` resolve in
//!    user code. (It is `crate::publications`, not `reiny::publications`, because types generated
//!    for the downstream crate cannot be injected into the foreign `reiny::` namespace.)
//! 2. **Start the runtime** — a synchronous `fn main` is emitted that runs the user's
//!    `async fn main(cloudy: Cloudy) -> reiny::Result<()>`, delegating the tokio runtime, the Zenoh
//!    session and signal shutdown to `reiny::run_with`.
//!
//! The one option is `#[reiny::main(tracing = false)]`, which stops reiny from installing a global
//! `tracing_subscriber` (for launches that bring their own).

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::parse::Parser;
use syn::{ItemFn, LitBool};

/// A launch's entry point. Put it on `async fn main(cloudy: Cloudy) -> reiny::Result<()>`.
///
/// `#[reiny::main(tracing = false)]` suppresses reiny's `tracing_subscriber` installation.
/// `tracing_subscriber::try_init` **does not take precedence when it runs later**, so this is the
/// only way for a launch with its own subscriber to avoid an ordering dependency on "install it
/// before reiny does".
#[proc_macro_attribute]
pub fn main(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand(attr.into(), item.into()).into()
}

/// The whole macro body, in `proc_macro2` terms so it is callable from tests (the `proc_macro`
/// types only exist inside a real compilation).
fn expand(attr: TokenStream2, item: TokenStream2) -> TokenStream2 {
    try_expand(attr, item).unwrap_or_else(syn::Error::into_compile_error)
}

fn try_expand(attr: TokenStream2, item: TokenStream2) -> syn::Result<TokenStream2> {
    let mut install_tracing = true;
    let attr_parser = syn::meta::parser(|meta| {
        if meta.path.is_ident("tracing") {
            install_tracing = meta.value()?.parse::<LitBool>()?.value();
            Ok(())
        } else {
            Err(meta.error("unknown #[reiny::main] option (only `tracing = false` is supported)"))
        }
    });
    attr_parser.parse2(attr)?;

    let user_fn: ItemFn = syn::parse2(item)?;

    // Require `async` — reiny's main is async.
    if user_fn.sig.asyncness.is_none() {
        return Err(syn::Error::new_spanned(
            user_fn.sig.fn_token,
            "#[reiny::main] requires an `async fn`",
        ));
    }

    // Move the user's fn aside under a private name (its own name is irrelevant; by convention it
    // is `main`). Signature and body are reused verbatim.
    let attrs = &user_fn.attrs;
    let inputs = &user_fn.sig.inputs;
    let output = &user_fn.sig.output;
    let body = &user_fn.block;

    Ok(quote! {
        // 1. The types generated by reiny-build, hoisted to the crate root. Referred to as
        //    `crate::publications::*` and friends.
        #[doc(hidden)]
        mod __reiny_generated {
            include!(concat!(env!("OUT_DIR"), "/reiny_generated.rs"));
        }
        #[allow(unused_imports)]
        pub use __reiny_generated::*;

        // 2. The synchronous entry point. Runtime construction, the Zenoh session and signal
        //    handling are all reiny's job.
        fn main() -> ::reiny::Result<()> {
            #(#attrs)*
            async fn __reiny_user_main(#inputs) #output #body

            let mut __opts = ::reiny::RuntimeOptions::from_args(env!("CARGO_PKG_NAME"));
            __opts.install_tracing = #install_tracing;
            ::reiny::run_with(__opts, __reiny_user_main)
        }
    })
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)] // tests may fail by panicking
mod tests {
    use super::*;

    /// A well-formed launch main, the shape every generated project has.
    fn user_main() -> TokenStream2 {
        quote! {
            async fn main(cloudy: Cloudy) -> reiny::Result<()> {
                Ok(())
            }
        }
    }

    fn expand_str(attr: TokenStream2, item: TokenStream2) -> String {
        expand(attr, item).to_string()
    }

    /// The expansion's two jobs, both of which downstream code depends on by name: the generated
    /// module is included at the crate root and re-exported (so `crate::publications::Ping`
    /// resolves), and a *synchronous* `fn main` hands the user's fn to `reiny::run_with`.
    #[test]
    fn expands_to_include_plus_sync_main() {
        let out = expand_str(TokenStream2::new(), user_main());
        assert!(out.contains("mod __reiny_generated"), "{out}");
        assert!(out.contains("reiny_generated.rs"), "{out}");
        assert!(out.contains("pub use __reiny_generated :: *"), "{out}");
        assert!(
            out.contains("fn main () -> :: reiny :: Result < () >"),
            "{out}"
        );
        assert!(out.contains(":: reiny :: run_with"), "{out}");
        // The user's own fn is renamed, so its `main` no longer collides with the emitted one.
        assert!(out.contains("async fn __reiny_user_main"), "{out}");
        assert!(!out.contains("compile_error"), "{out}");
    }

    /// The user's signature and body survive verbatim — the macro only moves the fn, it never
    /// rewrites it.
    #[test]
    fn preserves_signature_body_and_attributes() {
        let item = quote! {
            #[doc = "the launch entry point"]
            #[allow(unused)]
            async fn main(cloudy: Cloudy) -> reiny::Result<()> {
                let answer = 42;
                Ok(())
            }
        };
        let out = expand_str(TokenStream2::new(), item);
        assert!(out.contains("cloudy : Cloudy"), "{out}");
        assert!(out.contains("let answer = 42"), "{out}");
        assert!(out.contains("the launch entry point"), "{out}");
        assert!(out.contains("allow (unused)"), "{out}");
    }

    /// `tracing` defaults to on, and `tracing = false` is the single supported knob. It reaches the
    /// runtime as `RuntimeOptions::install_tracing`, so the literal has to land in the expansion.
    #[test]
    fn tracing_option_drives_install_tracing() {
        let default = expand_str(TokenStream2::new(), user_main());
        assert!(default.contains("install_tracing = true"), "{default}");

        let off = expand_str(quote! { tracing = false }, user_main());
        assert!(off.contains("install_tracing = false"), "{off}");

        let on = expand_str(quote! { tracing = true }, user_main());
        assert!(on.contains("install_tracing = true"), "{on}");
    }

    /// A non-async fn is the mistake people actually make; it has to fail as a readable
    /// `compile_error!`, not as a type error deep inside `run_with`.
    #[test]
    fn rejects_non_async_fn() {
        let item = quote! {
            fn main(cloudy: Cloudy) -> reiny::Result<()> { Ok(()) }
        };
        let out = expand_str(TokenStream2::new(), item);
        assert!(out.contains("compile_error"), "{out}");
        assert!(out.contains("requires an `async fn`"), "{out}");
    }

    /// An unknown option names itself rather than being ignored — a silent no-op on a misspelled
    /// `tracing` would leave the launch installing a subscriber it asked not to have.
    #[test]
    fn rejects_unknown_option() {
        let out = expand_str(quote! { tracing_ = false }, user_main());
        assert!(out.contains("compile_error"), "{out}");
        assert!(out.contains("unknown #[reiny::main] option"), "{out}");
    }

    /// `tracing` takes a bool literal; anything else is a parse error, not a coercion.
    #[test]
    fn rejects_non_bool_tracing_value() {
        let out = expand_str(quote! { tracing = "false" }, user_main());
        assert!(out.contains("compile_error"), "{out}");
    }

    /// Attached to something that is not a function at all, the error comes from `syn` rather than
    /// from a panic inside the macro.
    #[test]
    fn rejects_non_fn_item() {
        let out = expand_str(TokenStream2::new(), quote! { struct NotAFn; });
        assert!(out.contains("compile_error"), "{out}");
    }
}
