//! The reiny SDK.
//!
//! A launch publishes and subscribes by **naming a type and nothing else**. The type → topic
//! mapping is generated from `Reiny.toml` by `reiny-build` (each launch's `build.rs`) and embedded by
//! implementing [`Topic`] for every type. User code never touches a topic name (a string).
//!
//! ```ignore
//! use reiny::prelude::*;
//! use crate::publications::Ping;        // generated by reiny-build
//! use crate::dependencies::pong::Pong;  // likewise
//!
//! #[reiny::main]
//! async fn main(cloudy: Cloudy) -> reiny::Result<()> {
//!     let pings = cloudy.publish::<Ping>()?;
//!     let mut pongs = cloudy.subscribe::<Pong>()?;
//!     // ...
//!     Ok(())
//! }
//! ```
//!
//! # Engines
//!
//! [`Cloudy`] reaches the bus through an [`engine::Engine`]. The default is zenoh
//! ([`engine::Zenoh`], feature `zenoh`). [`engine::Local`] is an in-process bus, so a launch can be
//! tested with no network at all — hand it to [`Cloudy::open`] through `RuntimeOptions::engine`.
//!
//! # The escape hatch
//!
//! zenoh features reiny does not wrap are reachable directly through [`Cloudy::session`]. The price
//! is that **zenoh is a public dependency of reiny** (`pub use zenoh`), so a zenoh major release is a
//! breaking change for reiny — past this point, zenoh's semver becomes yours.

use std::sync::Arc;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

// Tests may express failure by panicking.
pub mod bridge;
#[cfg(all(test, feature = "zenoh"))]
#[allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]
mod e2e;
pub mod engine;
mod pubsub;
#[cfg(all(test, feature = "zenoh"))]
#[allow(clippy::expect_used, clippy::panic, clippy::unwrap_used)]
mod rpc_e2e;
mod runtime;
mod service;
mod shutdown;

use engine::{Engine, Guard, Key, SERVICE_CHUNK, SUB_CHUNK};
use shutdown::Shutdown;

pub use pubsub::{
    Envelope, Presence, PresenceEvent, Publisher, PublisherBuilder, Subscriber, SubscriberBuilder,
    SubscriberStats,
};
#[cfg(feature = "zenoh")]
pub use runtime::ZenohSource;
pub use runtime::{DOMAIN_ENV, RuntimeOptions, run_with};
pub use service::{CallError, Caller, CallerBuilder, Request, Server};

/// The type vocabulary lives in `reiny-core` (`no_std`), so that places where zenoh does not run
/// (`reiny-link`'s MCU side) share the same traits. The downstream path is still `reiny::Topic`.
pub use reiny_core::{Descriptor, Durability, History, Priority, Qos, Reliability, Service, Topic};

/// zenoh itself. Re-exported so that code using [`Cloudy::session`] cannot end up on a different
/// zenoh version than the one reiny links against.
#[cfg(feature = "zenoh")]
pub use zenoh;

/// `#[reiny::main]` — a launch's entry-point attribute. See [`reiny_macros::main`] for the details.
pub use reiny_macros::main;

/// The one line to put in a shared schema crate's `lib.rs` (`[schema] crate = ...`).
///
/// In workspace mode, the crate that prost-compiles `[internals]` and writes the `impl Topic`s
/// **exactly once** pulls `reiny-build`'s output (`$OUT_DIR/reiny_generated.rs`) in as a library and
/// exposes `internals` / `__pb`. A consuming launch only takes a Cargo dependency on that crate and
/// recompiles no protos of its own (the same mechanism `#[reiny::main]` uses to include them).
///
/// ```ignore
/// // myapp-schema/src/lib.rs
/// reiny::schema!();
/// // → myapp_schema::internals::* is now available to every other launch
/// ```
#[macro_export]
macro_rules! schema {
    () => {
        #[doc(hidden)]
        mod __reiny_generated {
            include!(concat!(env!("OUT_DIR"), "/reiny_generated.rs"));
        }
        #[allow(unused_imports)]
        pub use __reiny_generated::*;
    };
}

/// Re-exported so the `config()` extension generated by `reiny-build` can read the settings table
/// without the downstream crate carrying a `toml` dependency (hidden, unlike prost).
#[doc(hidden)]
pub use toml as __toml;

/// Called by that generated `config()` when an override in `--config` does not apply, so a typo or
/// a wrong type shows up in the log instead of silently becoming the `[config]` default.
#[doc(hidden)]
pub mod __config {
    /// The key is in `[config]` but the value's type is not the declared one.
    pub fn warn_type(key: &str, expected: &str, value: &toml::Value) {
        tracing::warn!(
            key,
            expected,
            found = value.type_str(),
            "--config: type mismatch, keeping the [config] default"
        );
    }

    /// The key is not in `[config]` at all.
    pub fn warn_unknown(key: &str) {
        tracing::warn!(key, "--config: unknown key ignored (not in [config])");
    }
}

/// reiny's result type. Failures all funnel into [`anyhow::Error`].
pub type Result<T> = anyhow::Result<T>;

/// The namespace (domain) used when none is given.
pub const DEFAULT_DOMAIN: &str = "default";

/// How long a presence query (`publishers()` and friends) waits before giving up. zenoh's `get` default.
const ALIVE_TIMEOUT: Duration = Duration::from_secs(10);
/// The startup "is this id already taken" query. Short enough not to delay startup.
const DUPLICATE_CHECK: Duration = Duration::from_millis(300);

/// A launch's runtime handle. `#[reiny::main]` builds it and hands it over.
///
/// It ties together the engine ([`engine::Engine`]), our instance id, the namespace, and cooperative shutdown.
/// `publish` / `subscribe` take **nothing but a type parameter**; the topic is resolved from [`Topic`].
pub struct Cloudy {
    engine: Arc<dyn Engine>,
    id: String,
    domain: String,
    shutdown: Shutdown,
    /// The launch's presence token (merely held; it disappears when the process dies).
    _launch: Guard,
    /// The settings file handed over with `--config <path>`, parsed (`None` if there was none).
    /// The `config()` extension `reiny-build` generates (the per-project `[config]`) reads it.
    config: Option<toml::Table>,
    /// The startup arguments reiny did not interpret (a launch's own `--port`, say).
    extra_args: Vec<String>,
}

impl Cloudy {
    /// Build on top of an engine. Declares the `@launch` token and warns when a launch with the same
    /// id is already there (it is not an error — impersonation such as `bag play --as` is deliberate).
    async fn new(
        engine: Arc<dyn Engine>,
        id: String,
        domain: String,
        shutdown: Shutdown,
        config: Option<toml::Table>,
        extra_args: Vec<String>,
    ) -> Result<Self> {
        let launch_key = Key::launch(&domain, Some(&id));
        if engine.caps().liveliness {
            if let Ok(alive) = engine.alive(&launch_key, DUPLICATE_CHECK).await
                && !alive.is_empty()
            {
                tracing::warn!(
                    id,
                    domain,
                    "another launch with the same id is already on the bus; \
                     both will publish under the same keys"
                );
            }
        } else {
            tracing::debug!(
                id,
                domain,
                "engine has no liveliness; launch presence is off"
            );
        }
        let launch = engine.declare_alive(&launch_key)?;
        Ok(Self {
            engine,
            id,
            domain,
            shutdown,
            _launch: launch,
            config,
            extra_args,
        })
    }

    /// A publisher for the type `T`, emitting to our own `reiny/<domain>/<id>/<T::TYPE>`.
    /// For `QoS` or latched, use the [`Cloudy::publisher`] builder.
    pub fn publish<T>(&self) -> Result<Publisher<T>>
    where
        T: prost::Message + Topic,
    {
        self.publisher::<T>().build()
    }

    /// A subscriber for the type `T`, subscribing to `reiny/<domain>/*/<T::TYPE>` (the same type from
    /// every publisher in the domain). To pick a source or to use latched, use [`Cloudy::subscriber`].
    pub fn subscribe<T>(&self) -> Result<Subscriber<T>>
    where
        T: prost::Message + Default + Topic,
    {
        self.subscriber::<T>().build()
    }

    /// A publisher builder for the type `T`. Stack `.latched()` and friends, then `.build()`.
    pub fn publisher<T>(&self) -> PublisherBuilder<'_, T> {
        PublisherBuilder::new(self)
    }

    /// A subscriber builder for the type `T`. Stack `.from(id)` / `.latched()`, then `.build()`.
    pub fn subscriber<T>(&self) -> SubscriberBuilder<'_, T> {
        SubscriberBuilder::new(self)
    }

    /// The launch ids currently publishing the type `T` (ourselves included, sorted by id).
    ///
    /// [`Cloudy::publish`] always accompanies a publisher with a liveliness token on the same key
    /// (there is no opt-out — allowing a publisher without one would make this return value
    /// untrustworthy), so an entry disappears the moment the process dies. No application-level
    pub async fn publishers<T: Topic>(&self) -> Result<Vec<String>> {
        self.alive_ids(self.key_for(None, T::TYPE)).await
    }

    /// The `<id>`s of the tokens alive on the liveliness key `key` (sorted, deduplicated).
    async fn alive_ids(&self, key: Key) -> Result<Vec<String>> {
        let mut ids: Vec<String> = self
            .engine
            .alive(&key, ALIVE_TIMEOUT)
            .await?
            .into_iter()
            .filter_map(|k| k.source)
            .collect();
        ids.sort();
        ids.dedup();
        Ok(ids)
    }

    /// Join / leave events for publishers of the type `T`. Publishers already alive when the watch is
    /// declared arrive first as [`PresenceEvent::Joined`] (history is on).
    pub fn watch_publishers<T: Topic>(&self) -> Result<Presence<T>> {
        self.watch_key(&self.key_for(None, T::TYPE))
    }

    /// The launch ids currently subscribed to the type `T` (ourselves included, ascending).
    ///
    /// The counterpart to [`Cloudy::publishers`], and the answer to the first question of every
    /// bring-up: "I am publishing and nothing reacts — is anyone actually listening?". Every
    /// subscriber carries a token at `reiny/<domain>/<id>/<T>/@sub`, so this needs no heartbeat
    /// either. It says who listens to the **type**, not who listens to whom: a subscriber narrowed
    /// with `.from(id)` still reports itself here.
    pub async fn subscribers<T: Topic>(&self) -> Result<Vec<String>> {
        self.alive_ids(self.key_for(None, T::TYPE).with_chunk(SUB_CHUNK))
            .await
    }

    /// Join / leave events for subscribers of the type `T` (the subscriber side of
    /// [`Cloudy::watch_publishers`]).
    ///
    /// This is how a publisher waits for its consumer instead of hoping: await the first `Joined`
    /// before the first `send`, and the message that "always gets lost at startup" cannot be.
    pub fn watch_subscribers<T: Topic>(&self) -> Result<Presence<T>> {
        self.watch_key(&self.key_for(None, T::TYPE).with_chunk(SUB_CHUNK))
    }

    /// The join / leave stream for the liveliness key `key` (existing declarations arrive as `Joined`).
    pub(crate) fn watch_key<T>(&self, key: &Key) -> Result<Presence<T>> {
        Presence::new(self, key)
    }

    /// Stand up a server for the request type `S`. It puts a queryable on
    /// `reiny/<domain>/<id>/<S::TYPE>`; take requests off [`Server::recv`] and answer with [`Request::reply`].
    pub fn serve<S: Service>(&self) -> Result<Server<S>> {
        Server::declare(self)
    }

    /// A caller builder for the request type `S`. Stack `.to(id)` / `.timeout(d)`, then `.build()`.
    pub fn caller<S: Service>(&self) -> CallerBuilder<'_, S> {
        CallerBuilder::new(self)
    }

    /// Call `S` once (any server in the domain, at the default timeout).
    /// Sugar over [`Cloudy::caller`].
    pub async fn call<S: Service>(
        &self,
        request: S,
    ) -> std::result::Result<S::Response, CallError> {
        self.caller::<S>().build().call(request).await
    }

    /// The launch ids currently serving the request type `S` (ourselves included, sorted by id).
    pub async fn servers<S: Service>(&self) -> Result<Vec<String>> {
        self.alive_ids(self.key_for(None, S::TYPE).with_chunk(SERVICE_CHUNK))
            .await
    }

    /// Join / leave events for servers of the request type `S` (the server side of [`Cloudy::watch_publishers`]).
    pub fn watch_servers<S: Service>(&self) -> Result<Presence<S>> {
        self.watch_key(&self.key_for(None, S::TYPE).with_chunk(SERVICE_CHUNK))
    }

    /// The engine underneath. Reach another engine's own features through `engine().as_any().downcast_ref::<E>()`.
    #[must_use]
    pub fn engine(&self) -> &Arc<dyn Engine> {
        &self.engine
    }

    /// A second `Cloudy` on **another engine**, sharing this one's id / domain / shutdown / config.
    /// The door through which a bridge (`reiny::bridge::forward`) holds "the zenoh `Cloudy`" and "the
    /// link `Cloudy`" in one process. The `@launch` token is declared on the new engine as well.
    pub async fn with_engine(&self, engine: Arc<dyn Engine>) -> Result<Self> {
        Self::new(
            engine,
            self.id.clone(),
            self.domain.clone(),
            self.shutdown.clone(),
            self.config.clone(),
            self.extra_args.clone(),
        )
        .await
    }

    /// The zenoh session inside. The escape hatch to features reiny does not wrap (queryables,
    /// scouting, attachments, pub/sub on arbitrary keys). `None` when the engine is not zenoh.
    ///
    /// Using it makes zenoh's semver yours — when reiny moves to a new zenoh major, the code that
    /// goes through here comes along for the ride.
    #[cfg(feature = "zenoh")]
    #[must_use]
    pub fn session(&self) -> Option<&zenoh::Session> {
        self.engine
            .as_any()
            .downcast_ref::<engine::Zenoh>()
            .map(engine::Zenoh::session)
    }

    /// Our own instance id (`--id` / `--name`, else `CARGO_PKG_NAME`).
    /// A launcher starting the same bin several times numbers them (`pong-1`, `pong-2`, …).
    #[must_use]
    pub fn id(&self) -> &str {
        &self.id
    }

    /// Our own logical namespace (`--domain` / `REINY_DOMAIN`, default [`DEFAULT_DOMAIN`]).
    /// Launches in different domains do not talk to each other, even on the same bus.
    #[must_use]
    pub fn domain(&self) -> &str {
        &self.domain
    }

    /// The startup arguments reiny did not interpret. A launch's own arguments (`--port` …) come from here.
    /// reiny does not reject unknown arguments — it cannot know them, and being strict would break every launch.
    #[must_use]
    pub fn extra_args(&self) -> &[String] {
        &self.extra_args
    }

    /// The current time (Unix seconds). A small convenience for message timestamps.
    #[must_use]
    pub fn now_unix(&self) -> i64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
    }

    /// The settings table handed over with `--config` (`None` if there was none). The raw material the
    /// typed `config()` extension `reiny-build` generates layers on top of `[config]`'s defaults.
    #[doc(hidden)]
    #[must_use]
    pub fn config_table(&self) -> Option<&toml::Table> {
        self.config.as_ref()
    }

    /// Wait until shutdown is requested (for a launch running its own loop).
    pub async fn shutdown(&self) {
        self.shutdown.wait().await;
    }

    /// Request shutdown ourselves (idempotent). A subscription loop's `recv` starts returning `None`
    /// and whoever waits in [`Cloudy::shutdown`] is released.
    pub fn shutdown_now(&self) {
        self.shutdown.trigger();
    }

    /// Build `reiny/<domain>/<source>/<ty>`. `source` is our own id, or `None` (= `*`).
    pub(crate) fn key_for(&self, source: Option<&str>, ty: &str) -> Key {
        Key::topic(&self.domain, source, ty)
    }

    pub(crate) fn shutdown_handle(&self) -> Shutdown {
        self.shutdown.clone()
    }
}

/// Validate that a name can be used as one segment of a key. A wildcard or a separator in there breaks
/// what the key means (it silently goes to a different topic), so reject it at startup.
fn validate_segment(what: &str, value: &str) -> Result<()> {
    if value.is_empty() {
        anyhow::bail!("{what} must not be empty");
    }
    if let Some(bad) = value
        .chars()
        .find(|c| matches!(c, '/' | '*' | '?' | '#' | '$' | '@') || c.is_whitespace())
    {
        anyhow::bail!(
            "{what} '{value}' contains '{bad}': it must be a single key segment \
             (no '/', '*', '?', '#', '$', '@' or whitespace)"
        );
    }
    Ok(())
}

/// The commonly used items, gathered. `use reiny::prelude::*;`
pub mod prelude {
    pub use crate::{
        CallError, Caller, Cloudy, Descriptor, Envelope, PresenceEvent, Priority, Publisher, Qos,
        Reliability, Request, Server, Service, Subscriber, Topic,
    };
}

/// The runtime `#[reiny::main]`'s expansion calls. Not meant to be touched directly.
#[doc(hidden)]
pub mod __rt {
    use std::future::Future;

    use crate::{Cloudy, Result, RuntimeOptions, run_with};

    /// The 0.2-compatible entry point. Builds [`RuntimeOptions`] from the arguments and hands them to [`run_with`].
    pub fn run<F, Fut>(default_name: &str, user: F) -> Result<()>
    where
        F: FnOnce(Cloudy) -> Fut,
        Fut: Future<Output = Result<()>>,
    {
        run_with(RuntimeOptions::from_args(default_name), user)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn segments_reject_wildcards_and_separators() {
        assert!(validate_segment("domain", "lab").is_ok());
        for bad in ["", "a/b", "*", "a*", "a b", "x?", "#", "$y", "a@b"] {
            assert!(
                validate_segment("domain", bad).is_err(),
                "should reject {bad:?}"
            );
        }
    }
}
