//! reiny's type vocabulary — `#![no_std]`.
//!
//! reiny's organizing principle is **type = topic**: a launch publishes and subscribes by naming
//! a Rust type. This crate holds only what a type needs in order to name itself — the traits
//! ([`Topic`] / [`Service`]), the descriptor ([`Descriptor`]) and the `QoS` vocabulary ([`Qos`]).
//! reiny proper (tokio / zenoh) is std-only, so the vocabulary was split out down here to let
//! places where zenoh does not run (`reiny-link` on an MCU) share type = topic.
//!
//! Normally you use what `reiny` re-exports. Only the MCU side depends on this crate directly,
//! and there it should be aliased in `Cargo.toml` as `reiny = { package = "reiny-core" }` so that
//! the `impl ::reiny::Topic for …` emitted by `reiny-build` resolves as-is.
//!
//! `prost` is pulled in `no_std` mode, so **alloc is required** (`Vec` / `String` fields).
// ponytail: alloc is required. Cut the trait when moving to micropb + heapless for alloc-free.

#![no_std]

mod qos;

pub use qos::{Durability, History, Priority, Qos, Reliability};

use prost::Message;

/// The type → topic mapping. `reiny-build` reads `Reiny.toml` and implements it for every message
/// type.
///
/// A topic is **addressed by type**. The type `Ping` is published to `reiny/<domain>/<id>/Ping`
/// and subscribed to as `reiny/<domain>/*/Ping` (the same type from every publisher in the same
/// domain). `<id>` is the runtime instance id, `<domain>` a logical namespace, and `TYPE` the type
/// segment of the key (e.g. `Ping`). The same type yields the same `TYPE` whichever crate — the
/// publisher's or the subscriber's — it is compiled in.
///
/// Engines other than zenoh do not necessarily render that key shape — `reiny-link` puts a 32-bit
/// hash of `TYPE` on the wire and has no `<domain>`. The single thing they all share is that
/// `TYPE` is the address.
pub trait Topic {
    /// The type segment of the topic key (e.g. `Ping`). Publishing goes to
    /// `reiny/<domain>/<id>/<TYPE>`, subscribing to `reiny/<domain>/*/<TYPE>`.
    const TYPE: &'static str;

    /// Schema fingerprint. Types generated by `reiny-build` carry a value computed from the proto
    /// descriptor.
    ///
    /// **Why it exists.** `TYPE` is the bare type name with the proto package stripped, so the
    /// topic namespace stays flat and a same-named type from another project can land on the same
    /// topic. protobuf is permissive, so when the field numbers happen to line up the **decode
    /// succeeds and the message is silently wrong**. The fingerprint is the only safety valve
    /// against that flatness: it rides in the zenoh attachment on publish and is checked on
    /// subscribe (when both sides are `Some` and differ, the sample is dropped after a single
    /// warning per source; if either side is `None` it passes through).
    ///
    /// It is defaulted, so a **hand-written `impl Topic` compiles unchanged** — that keeps reiny's
    /// promise intact: a third party joins the bus by writing `impl Topic` for their own type and
    /// nothing else.
    const SCHEMA: Option<u64> = None;

    /// The proto descriptor. Types generated by `reiny-build` point at their own crate's
    /// descriptor set.
    ///
    /// Publishing a type whose value is `Some` makes the publisher declare one queryable beside
    /// its key, at `reiny/<domain>/<id>/<TYPE>/@schema/<message>`, answering it with that
    /// descriptor set. This is how a running launch **names its own types on the bus**:
    /// `reiny bag record` picks it up and embeds the schema in the MCAP, producing a bag Foxglove
    /// can decode as-is (`docs/design/bag.md` §5).
    ///
    /// `@schema` is a zenoh verbatim chunk, so it is invisible both to a `reiny/<domain>/**`
    /// subscriber and to a `reiny/<domain>/*/*` recording — the type's own topic stays clean.
    const DESCRIPTOR: Option<Descriptor> = None;
}

/// The contents of [`Topic::DESCRIPTOR`] — the fully qualified proto message name plus the encoded
/// `google.protobuf.FileDescriptorSet` that contains it.
#[derive(Debug, Clone, Copy)]
pub struct Descriptor {
    /// Fully qualified message name (e.g. `hs.RobotState`). Used verbatim as the MCAP schema name.
    pub message: &'static str,
    /// The encoded `FileDescriptorSet`. Holds `message`'s own file and its transitive imports.
    pub file_set: &'static [u8],
}

/// request type → response type. The request type's [`Topic::TYPE`] is the type segment of the
/// key.
///
/// `reiny-build` generates the impls from `Reiny.toml`'s `[services]`. Writing one by hand is a
/// single line:
///
/// ```ignore
/// impl reiny::Service for Add { type Response = Sum; }
/// ```
///
/// `Response: Topic` is required so the reply carries a `SCHEMA` fingerprint of its own.
pub trait Service: Topic + Message + Default {
    /// The response type.
    type Response: Topic + Message + Default;
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)] // tests may fail by panicking
mod tests {
    use super::*;
    use prost::DecodeError;
    use prost::bytes::{Buf, BufMut};
    use prost::encoding::{DecodeContext, WireType, skip_field};

    /// An empty prost message, written by hand. This is deliberately *not* `reiny-build` output:
    /// these tests exercise the "a third party joins the bus by writing the impls themselves"
    /// path, with no codegen anywhere in sight.
    macro_rules! empty_message {
        ($name:ident) => {
            #[derive(Debug, Default, Clone, PartialEq, Eq)]
            struct $name;

            impl Message for $name {
                fn encode_raw(&self, _buf: &mut impl BufMut) {}
                fn merge_field(
                    &mut self,
                    tag: u32,
                    wire_type: WireType,
                    buf: &mut impl Buf,
                    ctx: DecodeContext,
                ) -> Result<(), DecodeError> {
                    skip_field(wire_type, tag, buf, ctx)
                }
                fn encoded_len(&self) -> usize {
                    0
                }
                fn clear(&mut self) {}
            }
        };
    }

    empty_message!(Add);
    empty_message!(Sum);

    impl Topic for Add {
        const TYPE: &'static str = "Add";
    }

    impl Topic for Sum {
        const TYPE: &'static str = "Sum";
    }

    impl Service for Add {
        type Response = Sum;
    }

    /// A hand-written `impl Topic` that sets only `TYPE` must compile, and both optional consts
    /// must default to `None` — that default is what lets a third-party type join the bus with no
    /// codegen at all.
    #[test]
    fn hand_written_topic_defaults_to_no_schema() {
        assert_eq!(Add::TYPE, "Add");
        assert!(Add::SCHEMA.is_none());
        assert!(Add::DESCRIPTOR.is_none());
    }

    /// A service addresses itself by its *request* type; the response type is reachable through
    /// the associated type and is a `Topic` in its own right (so replies carry a fingerprint).
    #[test]
    fn service_addresses_by_request_type() {
        assert_eq!(<Add as Service>::Response::TYPE, "Sum");
        // The key segment is the request type's, never the response type's.
        assert_ne!(Add::TYPE, <Add as Service>::Response::TYPE);
    }

    /// Both optional consts are overridable and `Descriptor` is `const`-constructible — that is
    /// exactly the shape `reiny-build` emits.
    #[test]
    fn descriptor_and_schema_are_overridable() {
        struct Generated;

        const FILE_SET: &[u8] = b"not-a-real-descriptor-set";

        impl Topic for Generated {
            const TYPE: &'static str = "Generated";
            const SCHEMA: Option<u64> = Some(0xdead_beef);
            const DESCRIPTOR: Option<Descriptor> = Some(Descriptor {
                message: "hs.Generated",
                file_set: FILE_SET,
            });
        }

        assert_eq!(Generated::SCHEMA, Some(0xdead_beef));
        let d = Generated::DESCRIPTOR.expect("DESCRIPTOR was set to Some");
        assert_eq!(d.message, "hs.Generated");
        assert_eq!(d.file_set, FILE_SET);
    }
}
